# Site settings
title: Yqsas Blog
SEOTitle: yqsas的博客 | Yqsas Blog
header-img: img/home-bg.jpg
email: yqsas@live.com
description: ""
keyword: "yqsas, blog, 博客, 个人网站, 互联网, Java"
url: "https://yqsas.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
# weibo_username:     
# zhihu_username:     
github_username: yqsas
# twitter_username:   
#facebook_username:  
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["assets","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN  

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# gem install jekyll-paginate
# gem install jekyll-sitemap
# gem install jekyll-toc https://github.com/toshimaru/jekyll-toc
plugins: [jekyll-paginate,jekyll-sitemap]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
# markdown: redcarpet
# redcarpet:
#     extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

# Disqus settings
# disqus_username: 

# Netease settings
# netease_comment: false

# Analytics settings
# Baidu Analytics 
ba_track_id: '8da711e2b50f28e6175f3b87778387d6'

# Google Analytics
ga_track_id: 'UA-131503678-1'            # Format: UA-xxxxxx-xx
ga_domain: yqsas.com

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "世界这么大，我想去看看"
sidebar-avatar: /img/yqsas.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    # {
    #     title: "xx",
    #     href: ""
    # },{
    #     title: "xxx",
    #     href: "http://xxx/"
    # }
]

bookmarks: [
    {
        title: "Martin Fowler",
        href: "https://martinfowler.com"
    },{
        title: "compress img",
        href: "http://www.bejson.com/ui/compress_img/"
    },{
        title: "unsplash",
        href: "https://unsplash.com"
    },{
        title: "Pxhere",
        href: "https://pxhere.com"
    }
]


